server:
  port: 8080
spring:
  application:
    name: inventory-service
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8080/eureka/
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 5
      metadataMap:
        instanceId: "${spring.application.name}:${random.value}"

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

security:
  oauth2:
    client:
      client-id: webshop-webclient
      client-secret: supersecretpassword
      access-token-uri: http://localhost:9208/oauth/token
      grant-type: authorization_code
      user-authorization-uri: http://localhost:9208/oauth/authorize
      scope: all.read all.write
    resource:
      jwk:
        key-set-uri: http://localhost:9208/oauth2/jwks.json