server:
  port: 8080
spring:
  application:
    name: product-composite
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    instance:
      preferIp-Address: true
      leaseRenewalIntervalInSeconds: 5
      metadataMap:
        instanceId: "${spring.application.name}:${random.value}"