server:
  port: 8080
spring:
  application:
    name: inventory-service
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8080/eureka/
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 5
      metadataMap:
        instanceId: "${spring.application.name}:${random.value}"

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
